2021-12-12 16:56:43,174 INFO: SMediApp startup [in /home/i1613/Backend_track/miniproj/app/__init__.py:43]
2021-12-12 16:57:52,729 INFO: SMediApp startup [in /home/i1613/Backend_track/miniproj/app/__init__.py:43]
2021-12-12 17:00:08,155 INFO: SMediApp startup [in /home/i1613/Backend_track/miniproj/app/__init__.py:43]
2021-12-12 17:26:48,858 INFO: SMediApp startup [in /home/i1613/Backend_track/miniproj/app/__init__.py:43]
2021-12-12 17:28:07,112 ERROR: Exception on /edit-post/2 [GET] [in /home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/i1613/Backend_track/miniproj/app/routes.py", line 45, in edit_Post
    return render_template('postEdit.html',id = id,post = post)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/i1613/Backend_track/miniproj/app/templates/postEdit.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/i1613/Backend_track/miniproj/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/i1613/Backend_track/miniproj/app/templates/postEdit.html", line 10, in block 'content'
    <a href="{{ url_for('postUpdate', id = id) }}"> <button type="button"> Update Post</button> </a>
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'postUpdate' with values ['id']. Did you mean 'postDelete' instead?
2021-12-12 17:28:14,260 ERROR: Exception on /edit-post/2 [GET] [in /home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/i1613/Backend_track/miniproj/app/routes.py", line 45, in edit_Post
    return render_template('postEdit.html',id = id,post = post)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/i1613/Backend_track/miniproj/app/templates/postEdit.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/i1613/Backend_track/miniproj/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/i1613/Backend_track/miniproj/app/templates/postEdit.html", line 10, in block 'content'
    <a href="{{ url_for('postUpdate', id = id) }}"> <button type="button"> Update Post</button> </a>
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'postUpdate' with values ['id']. Did you mean 'postDelete' instead?
2021-12-12 17:28:26,736 ERROR: Exception on /edit-post/2 [GET] [in /home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/i1613/Backend_track/miniproj/app/routes.py", line 45, in edit_Post
    return render_template('postEdit.html',id = id,post = post)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/i1613/Backend_track/miniproj/app/templates/postEdit.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/i1613/Backend_track/miniproj/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/i1613/Backend_track/miniproj/app/templates/postEdit.html", line 10, in block 'content'
    <a href="{{ url_for('postUpdate', id = id) }}"> <button type="button"> Update Post</button> </a>
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/i1613/Backend_track/miniproj/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'postUpdate' with values ['id']. Did you mean 'postDelete' instead?
2021-12-12 17:29:05,290 INFO: SMediApp startup [in /home/i1613/Backend_track/miniproj/app/__init__.py:43]
